routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('employee', EmployeeController::class);
Route::resource('company', CompanyController::class);
Route::get('/emplo/export/', 'EmployeeController@export')->name('exportemployee');

Route::view('/', 'app');
Route::view('/desa', 'app');
//Provinsi Route
Route::view('/provinsi', 'app');
Route::view('/provinsi/create', 'app');
Route::view('/provinsi/{id}/edit', 'app');
Route::view('/provinsi/{id}/update', 'app');
Route::view('/provinsi/{id}/delete', 'app');
//Kabupaten Route
Route::view('/kabupaten', 'app');
Route::view('/kecamatan', 'app');
Route::view('/reservasi', 'app');
Route::view('/film', 'app');
Route::view('/pesanfilm', 'app');
Route::view('/people', 'app');

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    protected $table = 'employee';
    protected $fillable = [
        'nama',
        'atasan_id',
        'company_id'
    ];

    // public function present_nama_atasan(){
    //     return $this->find($this->atasan_id)->nama;
    // }
    // public function present_nama_company(){
    //     $company = $this->company;
    //     return $company->nama;
    // }
    public function bawahan(){
        return $this->hasMany(self::class,'atasan_id');
    }
    public function atasan(){
        return $this->belongsTo(self::class,'atasan_id');
    }
    public function company(){
        return $this->BelongsTo('App\Models\Company','company_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;
use App\Exports\EmployeeExport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    public function export(Request $request)
    {
        if($request->get('type')=='pdf'){
            return Excel::download(new EmployeeExport, 'employee.pdf');
        }
        if($request->get('type')=='excel'){
            return Excel::download(new EmployeeExport, 'employee.xlsx');
        }
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employee = Employee::all();
        // dd($employee->atasan()->nama);
        return view('employee.index',['employee' => $employee]);
    }
    private function _validate(Request $request){
        $validatedData = $request->validate([
            'nama' => 'required|min:2|max:50'
        ]);
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $company = Company::all();
        $atasan = Employee::all();
        return view('employee.create',['company' => $company,'atasan' => $atasan]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $all = $request->all();
        $this->_validate($request);
        if ($request->input('atasan_id')=='null') {
            unset($all['atasan_id']);
        }
        Employee::create($all);
        return redirect()->route('employee.index')->with('success','Data Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::all();
        $atasan = Employee::all();

        $employee = Employee::find($id);
    return view('employee.edit',['employee' => $employee,'company' => $company,'atasan' => $atasan]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->_validate($request);
        $employee = Employee::find($id);
        if ($all['atasan_id']=='null') {
            unset($all['atasan_id']);
        }
        $employee->update($all);
        return redirect()->route('employee.index')->with('success','Data Berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $employee = Employee::find($id);
        $employee->delete();
        return redirect()->route('employee.index')->with('success','Data Berhasil dihapus');
    }
}

resources/views/employee/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Employee</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

</head>

<body>

<div class="container py-3">
    <div class="card w-50 mx-auto">
        <h5 class="card-header">Tambah Employe</h5>
        <div class="card-body">
            <form action="{{ route('employee.store') }}" method="POST">
                @csrf
                <div class="form-group mb-3">
                    <label for="nama">Nama :</label>
                    <input type="text" id="nama" class="form-control" name="nama" placeholder="Bambang Sutisna">
                </div>
                <div class="form-group mb-3">
                    <label for="atasan">Atasan :</label>
                    <select name="atasan_id" class="form-control" id="atas">
                        <option value="null">tidak memiliki atasan</option>
                        @foreach ($atasan as $item)
                            <option value="{{ $item->id }}">{{ $item->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group mb-3">
                    <label for="company">Company :</label>
                    <select name="company_id" id="atas" class="form-control">
                        @foreach ($company as $item)
                            <option value="{{ $item->id }}">{{ $item->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group mb-3 d-grid">
                    <input type="submit" class="btn btn-primary" value="simpan">
                </div>
            </form>
        </div>
    </div>
</div>

{{--  Js  --}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>
</body>

</html>

resources/views/employee/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Employee</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

</head>

<body>
<div class="container py-3">
    <div class="card w-50 mx-auto">
        <h5 class="card-header">Tambah Employe</h5>
        <div class="card-body">
            <form action="{{ route('employee.update',$employee->id) }}" method="POST">
                @csrf
                @method('put')
                <div class="form-group mb-3">
                    <label for="nama">Nama :</label>
                    <input type="text" id="nama" class="form-control" name="nama" value="{{$employee->nama}}" placeholder="Bambang Sutisna">
                </div>
                <div class="form-group mb-3">
                    <label for="atasan">Atasan :</label>
                    <select name="atasan_id" class="form-control" id="atas">
                        <option value="null">tidak memiliki atasan</option>
                        @foreach ($atasan as $item)
                            <option @if ($employee->atasan_id == $item->id)
                                    selected
                                    @endif value="{{ $item->id }}">{{ $item->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group mb-3">
                    <label for="company">Company :</label>
                    <select name="company_id" id="atas" class="form-control">
                        @foreach ($company as $item)
                            <option @if ($employee->company_id == $item->id)
                                    selected
                                    @endif value="{{ $item->id }}">{{ $item->nama }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group mb-3 d-grid">
                    <input type="submit" class="btn btn-primary" value="simpan">
                </div>
            </form>
        </div>
    </div>
</div>

{{--  Js  --}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>
</body>

</html>

resources/views/employee/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Employee</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>

<body>

<div class="container py-3">
    @if ($message = Session::get('success'))
        <div class="alert alert-success" role="alert">
            {{$message}}
        </div>
    @endif

    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h3 class="m-0 p-0">List Employes</h3>

            <div class="wrapper-button">
                <a href="{{ route('employee.create') }}" class="btn btn-primary btn-sm">Tambah</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>id</th>
                    <th>nama</th>
                    <th class="text-left">posisi</th>
                    <th class="text-left">perusahaan</th>
                    <th class="text-center" style="width: 200px">aksi</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($employee as $no => $item)
                    <tr>
                        <td>{{ $item->id }}</td>
                        <td>{{ $item->nama }}</td>
                        @if ($item->atasan)
                            <td class="text-left">{{ $item->atasan->nama }}</td>
                        @else
                            <td class="text-left">-</td>
                        @endif
                        <td class="text-left">{{ $item->company->nama }}</td>
                        <td class="d-flex justify-content-center">
                            <a href="{{ route('employee.edit', $item->id) }}" class="mx-2 btn btn-warning btn-sm">Edit</a>
                            <form action="{{ route('employee.destroy', $item->id) }}" method="POST">
                                @csrf
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="submit" class="btn btn-sm btn-danger" value="Hapus">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div class="wrapper-export-button">
                <a href="{{route('exportemployee')}}?type=pdf" class="btn btn-sm btn-warning px-3 font-weight-bold mx-2">Export data by pdf</a>
                <a href="{{route('exportemployee')}}?type=excel" class="btn btn-sm btn-info px-3 font-weight-bold mx-2">Export data by excel</a>
            </div>
        </div>
    </div>
</div>

{{-- Js    --}}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj"
        crossorigin="anonymous"></script>
</body>

</html>