routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('employee', EmployeeController::class);
Route::resource('company', CompanyController::class);
Route::get('/emplo/export/', 'EmployeeController@export')->name('exportemployee');

Route::view('/', 'app');
Route::view('/desa', 'app');
//Provinsi Route
Route::view('/provinsi', 'app');
Route::view('/provinsi/create', 'app');
Route::view('/provinsi/{id}/edit', 'app');
Route::view('/provinsi/{id}/update', 'app');
Route::view('/provinsi/{id}/delete', 'app');
//Kabupaten Route
Route::view('/kabupaten', 'app');
Route::view('/kecamatan', 'app');
Route::view('/reservasi', 'app');
Route::view('/film', 'app');
Route::view('/pesanfilm', 'app');
Route::view('/people', 'app');

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'company';
    protected $fillable = [
        'nama',
        'alamat'
    ];
    public function employee(){
        return $this->hasOne('\App\Models\Employee','company_id');
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $company = Company::all();
        return view('company.index',['company'=>$company]);
    }
    private function _validate(Request $request){
        $validatedData = $request->validate([
            'nama' => 'required|min:2|max:50',
            'alamat' => 'required|min:2|max:50'
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('company.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = $request->all();
        $this->_validate($request);

        Company::create($company);
        return redirect()->route('company.index')->with('success','Data Berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::find($id);
        return view('company.edit',['company' => $company]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->_validate($request);
        $company = Company::find($id);
        $company->update($request->all());
        return redirect()->route('company.index')->with('success','Data Berhasil diubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $company = Company::find($id);
        $company->delete();
        return redirect()->route('company.index')->with('success','Data Berhasil dihapus');
    }
}

resources/views/company/create.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tambah Company</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

</head>

<body>
    <div class="container py-2">
        <div class="card w-50 mx-auto">
            <h5 class="card-header">Tambah Company</h5>
            <div class="card-body">
                <form action="{{ route('company.store') }}" method="POST">
                    @csrf
                    <div class="form-group mb-3">
                        <label for="nama">Nama :</label>
                        <input type="text" id="nama" class="form-control" name="nama" placeholder="Javan Cipta Solusi">
                    </div>
                    <div class="form-group mb-3">
                        <label for="alamat">Alamat :</label>
                        <input type="text" id="alamat" class="form-control" name="alamat" placeholder="D.I.Yogyakarta">
                    </div>
                    <div class="form-group mb-3 d-grid">
                        <input type="submit" class="btn btn-primary" value="simpan">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>

resources/views/company/edit.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Company</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">

</head>

<body>
<div class="container py-3">
    <div class="card w-50 mx-auto">
        <h5 class="card-header">Edit Company</h5>
        <div class="card-body">
            <form action="{{ route('company.update',$company->id) }}" method="POST">
                @csrf
                @method('put')
                <div class="form-group mb-3">
                    <label for="nama">Nama :</label>
                    <input type="text" id="nama" class="form-control" name="nama" value="{{$company->nama}}" />
                </div>
                <div class="form-group mb-3">
                    <label for="">Alamat</label>
                    <input type="text" class="form-control" name="alamat" placeholder="Alamat" value="{{$company->alamat}}">
                </div>
                <div class="form-group mb-3 d-grid">
                    <input type="submit" class="btn btn-primary" value="simpan">
                </div>
            </form>
        </div>
    </div>
</div>
</body>

</html>

resources/views/company/index.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Company</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
</head>

<body>

    <div class="container py-3">
        @if ($message = Session::get('success'))
            <div class="alert alert-success" role="alert">
                {{$message}}
            </div>
        @endif

        <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h3 class="m-0 p-0">List Company</h3>

            <div class="wrapper-button">
                <a href="{{ route('company.create') }}" class="btn btn-primary btn-sm">Tambah</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th class="text-center">no</th>
                    <th>nama</th>
                    <th class="text-center">alamat</th>
                    <th class="text-center" style="width: 200px">aksi</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($company as $no => $item)
                    <tr>
                        <td class="text-center">{{ $no+1 }}.</td>
                        <td>{{ $item->nama }}</td>
                        <td class="text-center">{{ $item->alamat }}</td>
                        <td class="d-flex justify-content-center">
                            <a href="{{ route('company.edit', $item->id) }}" class="mx-2 btn btn-warning btn-sm">Edit</a>
                            <form action="{{ route('company.destroy', $item->id) }}" method="POST">
                                @csrf
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="submit" class="btn btn-sm btn-danger" value="Hapus">
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    </div>
</body>

</html>